# Generated by Django 5.1 on 2024-09-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_noticia_alter_post_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=150)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
