# Generated by Django 5.1 on 2024-09-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
