# Generated by Django 5.1 on 2024-10-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='a', max_length=2000),
            preserve_default=False,
        ),
    ]
